### ISSUE TITLE
Showing Wrong Time For Game Dev Fridays

### ISSUE THREAD

**Issue by JimLynchCodes** [mobusoperandi/website#261]
Hey @mightyiam, we merged this: https://github.com/mobusoperandi/website/pull/260

but the website it still showing it at the wrong time... it should be at 3pm based on the yaml in main branch now 🤔

<img width="1221" alt="Screenshot 2024-09-19 at 12 06 45 AM" src="https://github.com/user-attachments/assets/d1ac29b5-df70-41a7-a258-337b1cbc2a56">

did it fail it build or deploy? can you add that stuff to display on github please. 

Is this line here the correct way to do US eastern time? https://github.com/mobusoperandi/website/blob/master/mobs/mobile_game_dev_fridays.yaml#L10

**Comment by mightyiam** [comment]
Sorry. Will look into it.

**Comment by mightyiam** [comment]
Here it is:
https://github.com/mobusoperandi/website/actions/runs/10857662314/job/30134447229#step:8:17

Which valid entry would be the most correct? Here's [the list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

**Comment by JimLynchCodes** [comment]
Thanks @mightyiam, I'm trying to do the time for "[America/New_York](https://en.wikipedia.org/wiki/America/New_York)". Let me try it just like that similar to the vienna example in mobrpg.yaml 👍
